API and List
Marcel-FR/capstone-project pull request #7
Opened 2023-03-07 13:26 UTC by Marcel-FR

This is the list of the bestiary.
It shows the name, type and challenge ratings of all Monsters.

This is not yet performant. I will fix this soon.

[Preview](https://capstone-project-git-api-and-list-marcel-fr.vercel.app)

[List US](https://github.com/Marcel-FR/capstone-project/issues/3), [API US](https://github.com/Marcel-FR/capstone-project/issues/5)

2023-03-07 14:05 UTC, Kheirah requested changes
Very good work!

You only need to think about fetching data in order to reduce loading times. See if you can change some code around with the help of my comment below.

2023-03-07 14:05 UTC, Kheirah commented on resources/lib/dnd-api.js
> +    })
That's the reason why the initial fetch takes several seconds to complete. After you fetch all monsters from `"https://www.dnd5eapi.co/api/monsters"` you then loop through ALL these monsters and initiate another fetch to retrieve more info about each monster. In effect, you are fetching 335 times! Once for the initial data and once for each of the 334 monsters.

To fix that, you can simply avoid fetching the additional info from each monster. You probably don't need to display their details on the bestiary page and can instead defer the fetch for detailed info into the detail page of each monster. That way, you're never fetching 335x.

2023-03-08 10:24 UTC, Marcel-FR commented on resources/lib/dnd-api.js
> +    })
I fixed that issue now.

2023-03-08 10:55 UTC, MelissaDuve approved these changes
nice!

2023-03-08 10:56 UTC, merged